# Generated by Django 5.2.1 on 2025-05-22 04:33

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(default='defaults/farm_default.jpg', upload_to='farms/', validators=[marketplace.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defaults/product_default.jpg', upload_to='products', validators=[marketplace.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaults/profile_default.jpg', upload_to='profile_pics/', validators=[marketplace.models.validate_image_size]),
        ),
    ]
